# rakuda_tools/config/init_pose.yaml
poses:
  home:
    move_time: 3.0         # secondi
    unit: rad              # rad 
    controllers:
      left_arm_controller:
        joints:
          - l_arm_joint1
          - l_arm_joint2
          - l_arm_joint3
          - l_arm_joint4
          - l_arm_joint5
          - l_arm_joint6
          - l_gripper_joint
        positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

      right_arm_controller:
        joints:
          - r_arm_joint1
          - r_arm_joint2
          - r_arm_joint3
          - r_arm_joint4
          - r_arm_joint5
          - r_arm_joint6
          - r_gripper_joint
        positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0,0.0]

      head_controller:
        joints:
          - neck_yaw_joint
          - neck_pitch_joint
        positions: [0.0, 0.0]

      torso_controller:
        joints:
          - waist_yaw_joint
        positions: [0.0]



  pos1:
    move_time: 2.0         # secondi
    unit: rad              # rad 
    controllers:
      left_arm_controller:
        joints:
          - l_arm_joint1
          - l_arm_joint2
          - l_arm_joint3
          - l_arm_joint4
          - l_arm_joint5
          - l_arm_joint6
          - l_gripper_joint
        positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0,0.0]

      right_arm_controller:
        joints:
          - r_arm_joint1
          - r_arm_joint2
          - r_arm_joint3
          - r_arm_joint4
          - r_arm_joint5
          - r_arm_joint6
          - r_gripper_joint
        positions: [0.0, -0.29, -0.30, 1.74, 0.0, 0.0,0.0]

      head_controller:
        joints:
          - neck_yaw_joint
          - neck_pitch_joint
        positions: [0.0, 0.0]

      torso_controller:
        joints:
          - waist_yaw_joint
        positions: [0.0]

  pos2:
    move_time: 0.5         # secondi
    unit: rad              # rad 
    controllers:
      left_arm_controller:
        joints:
          - l_arm_joint1
          - l_arm_joint2
          - l_arm_joint3
          - l_arm_joint4
          - l_arm_joint5
          - l_arm_joint6
          - l_gripper_joint
        positions: [0.0, 0.29, 0.30, -1.74, 0.0, 0.0, 0.0]

      right_arm_controller:
        joints:
          - r_arm_joint1
          - r_arm_joint2
          - r_arm_joint3
          - r_arm_joint4
          - r_arm_joint5
          - r_arm_joint6
          - r_gripper_joint
        positions: [0.0, -0.29, -0.30, 1.74, 0.0, 0.0, 0.0]

      head_controller:
        joints:
          - neck_yaw_joint
          - neck_pitch_joint
        positions: [0.0, 0.0]

      torso_controller:
        joints:
          - waist_yaw_joint
        positions: [0.0]

  pos3:
    move_time: 0.5         # secondi
    unit: rad              # rad 
    controllers:
      left_arm_controller:
        joints:
          - l_arm_joint1
          - l_arm_joint2
          - l_arm_joint3
          - l_arm_joint4
          - l_arm_joint5
          - l_arm_joint6
          - l_gripper_joint
        positions: [0.0, 1.31, 0.0, -1.74, 0.0, 0.0, 0.60]

      right_arm_controller:
        joints:
          - r_arm_joint1
          - r_arm_joint2
          - r_arm_joint3
          - r_arm_joint4
          - r_arm_joint5
          - r_arm_joint6
          - r_gripper_joint
        positions: [0.0, -1.31, -0.0, 1.74, 0.0, 0.0, -0.60]

      head_controller:
        joints:
          - neck_yaw_joint
          - neck_pitch_joint
        positions: [0.0, 0.0]

      torso_controller:
        joints:
          - waist_yaw_joint
        positions: [0.0]

  close_gripper:
    move_time: 1.0         # secondi
    unit: rad              # rad 
    controllers:
      left_arm_controller:
        joints:
          - l_gripper_joint
        positions: [0.0,]

      right_arm_controller:
        joints:
          - r_gripper_joint
        positions: [0.0]

  open_gripper:
    move_time: 1.0         # secondi
    unit: rad              # rad 
    controllers:
      left_arm_controller:
        joints:
          - l_gripper_joint
        positions: [0.60]

      right_arm_controller:
        joints:
          - r_gripper_joint
        positions: [-0.60]