controller_manager:
  ros__parameters:
    use_sim_time: False
    update_rate: 100 #Hz

    torso_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    head_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


torso_controller:
  ros__parameters:
    joints:
      - waist_yaw_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: true
    allow_nonzero_velocity_at_trajectory_end: false
    open_loop_control: false
    interpolate_from_desired_state: true

    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.5
      waist_yaw_joint:
        trajectory: 0.2
        goal: 0.05


head_controller:
  ros__parameters:
    joints:
      - neck_yaw_joint
      - neck_pitch_joint

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0
    command_timeout: 0.5

